import type { Metadata } from "next";


import { Providers } from "./provider";
import Navbar from "./navbar";


export const metadata: Metadata = {
  title: "Todo app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      
      <body >
<Navbar />
        
        <Providers>{children}</Providers></body>
    </html>
  );
}
